[WIP] Input type color
metadevpro/lux pull request #175
Opened 2022-01-03 11:39 UTC by JavierCenteno

[WIP] Implementing type color in lux-input

2022-01-03 15:58 UTC, pjmolina requested changes
some changes needed. broken tests

2022-01-03 15:58 UTC, pjmolina commented on projects/lux/src/lib/helperFns.ts
> +  return CSS.supports('color', value);
This is smart!
https://developer.mozilla.org/en-US/docs/Web/API/CSS/supports
I didn't know it.

2022-01-03 15:58 UTC, pjmolina commented on projects/lux/src/lib/helperFns.spec.ts
> +    expect(isValidColor('rgb(0,0,255)')).toBeTrue();
test also with spaces: example:  `'  rgb  ( 0 , 0,   255   )  '`

2022-01-03 15:58 UTC, pjmolina commented on projects/lux/src/lib/helperFns.spec.ts
> +    expect(isValidUrl('https://www.com//')).toBeFalse();
this is valid (see test execution)

2022-01-03 15:58 UTC, pjmolina commented on projects/lux/src/lib/helperFns.spec.ts
> +    expect(isValidColor('#0123')).toBeFalse();
this is valid: see test execution. valid format `#rgba`  with alpha channel

2022-01-03 15:58 UTC, pjmolina commented on projects/lux/src/lib/helperFns.spec.ts
> +    expect(isValidColor('#01234567')).toBeFalse();
this is valid. see test execution: due to alpha channel:    `#rrggbbaa`

2022-01-04 03:33 UTC, JavierCenteno commented on projects/lux/src/lib/helperFns.spec.ts
> +    expect(isValidColor('rgb(0,0,255)')).toBeTrue();
Added: https://github.com/metadevpro/lux/pull/175/commits/39e52a6faa602556b59a579b4e341371e48ab627

2022-01-04 09:36 UTC, merged