Improve icons of datetime and geolocation
metadevpro/lux pull request #177
Opened 2022-01-10 09:56 UTC by JavierCenteno

- Give the icon to open the map modal its own box
- Make clear icon disappear if there's no value to clear

2022-01-10 12:23 UTC, pjmolina requested changes
remove CSS rule with *

2022-01-10 12:23 UTC, pjmolina commented on projects/lux/src/lib/styles/lux.scss
> +* {
evitar usar reglas con asterisco -> impacto global

2022-01-10 12:25 UTC, JavierCenteno commented on projects/lux/src/lib/styles/lux.scss
> +* {
Quitada, voy a usar alternativas

2022-01-11 18:08 UTC, pjmolina approved these changes

2022-01-11 18:08 UTC, merged