Voice recognition
metadevpro/lux pull request #22
Opened 2019-09-05 01:07 UTC by Chanell13

2021-04-13 16:37 UTC, Foxandxss requested changes
For me missing:

Warning to say that only works on chrome right now
I would add a dropdown in the demo to select other languages. We can't show the doc in English and the demo in Spanish.

2021-04-13 16:37 UTC, Foxandxss commented on src/app/voicerecognition-sample/voicerecognition-sample.component.html
> +<p>VoiceRecongnition is implemented as a directive. Therefore it can extend any input or textarea to allow voice input whenever text is accepted.</p>
VoiceRecognition

2021-04-13 16:37 UTC, Foxandxss commented on src/app/voicerecognition-sample/voicerecognition-sample.component.html
> +<p>Laguage must be configured to improve recognition accuracy.</p>
Language

2021-04-14 07:59 UTC, pjmolina commented on src/app/voicerecognition-sample/voicerecognition-sample.component.html
> +<p>VoiceRecongnition is implemented as a directive. Therefore it can extend any input or textarea to allow voice input whenever text is accepted.</p>
Fair points. I will add them.

2021-04-14 08:51 UTC, pjmolina commented on src/app/voicerecognition-sample/voicerecognition-sample.component.html
> +<p>VoiceRecongnition is implemented as a directive. Therefore it can extend any input or textarea to allow voice input whenever text is accepted.</p>
added

2021-04-14 08:51 UTC, pjmolina commented on src/app/voicerecognition-sample/voicerecognition-sample.component.html
> +<p>Laguage must be configured to improve recognition accuracy.</p>
fixed

2021-04-14 14:32 UTC, merged